# Generated by Django 4.2.11 on 2024-03-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_about_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
